<?php

########################################################################
# Extension Manager/Repository config file for ext "css_select".
#
# Auto generated 27-09-2011 03:50
#
# Manual updates:
# Only the data in the array - everything else is removed by next
# writing. "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Page StyleSheet Selector',
	'description' => 'Select one or more stylesheet(s) for each page of the tree... The goal of this extension is to drastically reduce the weight of the pages generated by TYPO3, by including only the styles needed in the page.',
	'category' => 'be',
	'shy' => 0,
	'version' => '6.2.0',
	'dependencies' => '',
	'conflicts' => '',
	'priority' => '',
	'loadOrder' => '',
	'TYPO3_version' => '',
	'PHP_version' => '5.3.7-5.5.x',
	'module' => '',
	'state' => 'stable',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => 'pages',
	'clearcacheonload' => 1,
	'lockType' => '',
	'author' => 'Sebastien Convers',
	'author_email' => 'sebastien.convers@educagri.fr',
	'author_company' => 'eduter-cnerta.fr',
	'CGLcompliance' => '',
	'CGLcompliance_note' => '',
        'constraints' => array(
            'depends' => array(
                'typo3' => '6.2.0-6.2.99',
            ),
            'conflicts' => array(
            ),
            'suggests' => array(
            ),
        ),
);

?>